### ISSUE TITLE
Man kann nicht zu Fuss zum Essen gehen

### ISSUE THREAD

**Issue by thorque** [innoq/FoodHub_issues#1]
Ich habe nur die Möglichkeit Essen liefern zu lassen oder mit dem Auto zu gehen. Eine weitere Option wäre noch zu Fuss.

**Comment by kintor** [comment]
Jetzt kannst du auch zu Fuß zu M.Rhein. Die Optionen lassen sich beim Erstellen eines Restaurant einstellen. Bei manchen Restaurant (L'Osteria z.B.) ist es weniger sinnvoll, laufen zu wollen.

**Comment by thorque** [comment]
Ist M.Rhein eigentlich Vater Rhein oder was anderes?
